### ISSUE TITLE
WSOD when customer registers due to Share Cart API issue

### ISSUE THREAD

**Issue by mattallenuk** [mageplaza/magento-2-share-cart#11]
I installed and configured the module onto my store now I am getting white screen of death whenever a customer registers. I checked my logs and this is the error being shown:

[Tue Jul 28 08:03:13.909165 2020] [proxy_fcgi:error] [pid 23161] [client 82.42.164.129:47778] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Quote\\Api\\Data\\CartExtension::getMpShareCartToken() in /public_html/vendor/mageplaza/module-share-cart/Plugin/Api/CartGet.php:89
Stack trace:\n#0 /public_html/vendor/mageplaza/module-share-cart/Plugin/Api/CartGet.php(67): Mageplaza\\ShareCart\\Plugin\\Api\\CartGet->setTokenToExtensionAttributes(Object(Magento\\Quote\\Model\\Quote\\Interceptor))
#1 /public_html/vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\\ShareCart\\Plugin\\Api\\CartGet->afterGet(Object(Magento\\Quote\\Model\\QuoteRepository\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Interceptor), '78', Array)
#2 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Quote\\Model\\QuoteRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}('78', Array)\n#3 /home/...', referer: https://www.webiste.com/customer/account/create/

If I disable the module in the Admin area the error still occurs so I have to remove the module. 

Magento version: 2.3.5-p1
Module Version: 1.1
Installed via Composer

**Comment by phamcuongmp** [comment]
Hello,
Please help me remove the generated folder and run the command php bin/magento setup:di:compile to resolve the problem.

**Comment by mattallenuk** [comment]
Thank you that worked. I must have forgotten to run those commands when I initially installed the module.
