### ISSUE TITLE
Stable release version for latest master commits

### ISSUE THREAD

**Issue by igorwulff** [mageplaza/magento-2-share-cart#13]
Hello! As the title says, we would like to use the most recent version of master. We see this isn't released/tagged yet. Can this be done? I have requested this some time ago as well. And be pushed into packagist?

**Comment by phamcuongmp** [comment]
We've merged your updates to the master branch. You are able to download and use it in the master branch.
We will release the new version shortly.
Thank you so much

**Comment by phamcuongmp** [comment]
I would love to inform you that we have already released the updated version of the Share Cart module. The modifications are launched now. Please download and try it out!
Thank you so much for your kind contribution. We truly appreciate your effort.
