### ISSUE TITLE
main.CRITICAL: Helper method

### ISSUE THREAD

**Issue by Mirifik** [mageplaza/magento-2-share-cart#15]
Hello Team,

I have issue with module, please help

[2021-01-04 09:16:41] main.CRITICAL: Helper method 'Mageplaza\ShareCart\Helper\Data::isDisabled' does not exist. [] []
[2021-01-04 09:16:41] main.ERROR: Class Mageplaza\TwoFactorAuth\Model\Auth does not exist

**Comment by Mirifik** [comment]
Issue with module
Frontend: http://prntscr.com/wfuadv
Backend: http://prntscr.com/wfuasl

**Comment by phamcuongmp** [comment]
We truly appreciate your business, and we’re grateful for the trust you’ve placed in us.
Regarding your issue, have you installed the Mageplaza Core module yet? If not, kindly help me download and install the Core module first via the following link: https://github.com/mageplaza/module-core

**Comment by Mirifik** [comment]
Thank you very much, 
I will follow your instructions and get back to you once everything is okay.

King regards!

**Comment by Mirifik** [comment]
Great,
I found my home page and the backend but the Slides, products and buttons are not displayed.
I looked at the symlink but it doesn't work.

Frontend: http://prntscr.com/wfvfl9
Backend:  http://prntscr.com/wfvenp

**Comment by phamcuongmp** [comment]
This issue is not relating to Mageplaza extensions. Your deploy processing might encounter some problems. Are you using any special cache? Please help me refresh the cache after running the deploy command line.

**Comment by Mirifik** [comment]
Okay I will try to flush cache

**Comment by phamcuongmp** [comment]
Besides, kindly add more permission for var/cache, pub/static and generated folder.

**Comment by Mirifik** [comment]
Hello @phamcuongmp 
After granting permissions to the folders, I always get the same result. 
I also can't disable your extension because the links are off.
It looks like a symlink issue. But it's not the case
http://prntscr.com/wfwg1b

Please help

**Comment by Mirifik** [comment]
Hi @phamcuongmp 

I check on exception.log and I this error line again :

main.CRITICAL: Class Mageplaza\TwoFactorAuth\Model\Auth does not exist {"report_id":"223936958559e1f610650516ee947bda6726a26158e2ba434f86b9c6c36bdf30","exception":"[object] (ReflectionException(code: -1): Class Mageplaza\TwoFactorAuth\Model\Auth does not exist at /home/ipcgenev/public_html/vendor/magento/framework/Code/Reader/ClassReader.php:26)"} []

**Comment by Mirifik** [comment]
Thank you everything works very well

**Comment by Mirifik** [comment]
by using this command line
php bin/magento s:up
php bin/magento s:s:d -f en_US fr_FR
php bin/magento c:f
